name: C/C++ CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: test normal
      run: ./build/picsorter test/ && ls test/
    - name: test recursive
      run: ./build/picsorter -r test/ && ls test/
    - name: make clean
      run: make clean
